//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptProxy
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public byte[] Content { get; set; }
        public int AcceptUserId { get; set; }
        public int Status { get; set; }
        public string Courier { get; set; }
        public string LeaveMessage { get; set; }
        public string CourierPhone { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> LastModifyUserId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
