//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetInfo
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public int AttributeId { get; set; }
        public string AttributeValue { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetAttribute AssetAttribute { get; set; }
    }
}
