//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransaction
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public int OutUserId { get; set; }
        public Nullable<bool> OutUserIsConfirm { get; set; }
        public int InUserId { get; set; }
        public Nullable<bool> InUserIsConfirm { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
