//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSummary
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Type { get; set; }
        public int Year { get; set; }
        public Nullable<double> LastValue { get; set; }
        public Nullable<double> BaseValue { get; set; }
        public Nullable<double> RemainValue { get; set; }
    }
}
