//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public string Type { get; set; }
        public string Desc { get; set; }
        public string Author { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Donor { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Reader { get; set; }
        public string BarCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
