//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseDetail()
        {
            this.ExpenseMembers = new HashSet<ExpenseMember>();
        }
    
        public int Id { get; set; }
        public int MId { get; set; }
        public System.DateTime ODate { get; set; }
        public int EType { get; set; }
        public string Remark { get; set; }
        public int PCount { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ExpenseMain ExpenseMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseMember> ExpenseMembers { get; set; }
    }
}
