//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAuditHistory
    {
        public int Id { get; set; }
        public int CurrentAudit { get; set; }
        public Nullable<int> NextAudit { get; set; }
        public int ExpenseId { get; set; }
        public Nullable<int> Status { get; set; }
        public string AuditMessage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ExpenseMain ExpenseMain { get; set; }
    }
}
