//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Desc { get; set; }
        public int ProblemType { get; set; }
        public string Title { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
