//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingCalendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingCalendar()
        {
            this.MeetingParticipants = new HashSet<MeetingParticipant>();
        }
    
        public int Id { get; set; }
        public int MeetingRoomId { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Host { get; set; }
        public string MeetingContext { get; set; }
        public string MeetingSummary { get; set; }
        public int Status { get; set; }
        public int ApplyUserId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual MeetingRoom MeetingRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }
    }
}
