//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MissionskyOAEntities : DbContext
    {
        public MissionskyOAEntities()
            : base("name=MissionskyOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcceptProxy> AcceptProxies { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetAttribute> AssetAttributes { get; set; }
        public virtual DbSet<AssetInfo> AssetInfoes { get; set; }
        public virtual DbSet<AssetInventory> AssetInventories { get; set; }
        public virtual DbSet<AssetInventoryRecord> AssetInventoryRecords { get; set; }
        public virtual DbSet<AssetTransaction> AssetTransactions { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AssetTypeAttribute> AssetTypeAttributes { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AttendanceSummary> AttendanceSummaries { get; set; }
        public virtual DbSet<AuditMessage> AuditMessages { get; set; }
        public virtual DbSet<Avatar> Avatars { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookBorrow> BookBorrows { get; set; }
        public virtual DbSet<BookComment> BookComments { get; set; }
        public virtual DbSet<DataDict> DataDicts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<ExpenseAuditHistory> ExpenseAuditHistories { get; set; }
        public virtual DbSet<ExpenseDetail> ExpenseDetails { get; set; }
        public virtual DbSet<ExpenseMain> ExpenseMains { get; set; }
        public virtual DbSet<ExpenseMember> ExpenseMembers { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MeetingCalendar> MeetingCalendars { get; set; }
        public virtual DbSet<MeetingParticipant> MeetingParticipants { get; set; }
        public virtual DbSet<MeetingRoom> MeetingRooms { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationTargetUser> NotificationTargetUsers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDet> OrderDets { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduledTask> ScheduledTasks { get; set; }
        public virtual DbSet<ScheduledTaskHistory> ScheduledTaskHistories { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Workflow> Workflows { get; set; }
        public virtual DbSet<WorkflowProcess> WorkflowProcesses { get; set; }
        public virtual DbSet<WorkflowStep> WorkflowSteps { get; set; }
        public virtual DbSet<WorkTask> WorkTasks { get; set; }
        public virtual DbSet<WorkTaskComment> WorkTaskComments { get; set; }
        public virtual DbSet<WorkTaskHistory> WorkTaskHistories { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportConfig> ReportConfigs { get; set; }
        public virtual DbSet<ReportParameter> ReportParameters { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int p_summaryAttendanceDetail(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_summaryAttendanceDetail", dateParameter);
        }
    }
}
