//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDet
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<double> IOHours { get; set; }
        public Nullable<bool> InformLeader { get; set; }
        public Nullable<bool> WorkTransfer { get; set; }
        public Nullable<int> Recipient { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public string Audit { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
