//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportConfig
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public string Config { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
