//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledTask()
        {
            this.ScheduledTaskHistories = new HashSet<ScheduledTaskHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Interval { get; set; }
        public int Unit { get; set; }
        public int Status { get; set; }
        public string TaskClass { get; set; }
        public string Desc { get; set; }
        public Nullable<System.DateTime> LastExecTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledTaskHistory> ScheduledTaskHistories { get; set; }
    }
}
