//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Assets = new HashSet<Asset>();
            this.Avatars = new HashSet<Avatar>();
            this.ExpenseMembers = new HashSet<ExpenseMember>();
            this.Feedbacks = new HashSet<Feedback>();
            this.MeetingParticipants = new HashSet<MeetingParticipant>();
            this.Orders = new HashSet<Order>();
            this.UserRoles = new HashSet<UserRole>();
            this.WorkflowProcesses = new HashSet<WorkflowProcess>();
        }
    
        public int Id { get; set; }
        public string No { get; set; }
        public string ChineseName { get; set; }
        public string EnglishName { get; set; }
        public string QQID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> DirectlySupervisorId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Position { get; set; }
        public string Token { get; set; }
        public Nullable<int> Status { get; set; }
        public bool Available { get; set; }
        public int TodayStatus { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public string AuthNotify { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ServerYear { get; set; }
        public Nullable<int> ServerYearType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avatar> Avatars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseMember> ExpenseMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowProcess> WorkflowProcesses { get; set; }
    }
}
