//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStep
    {
        public int Id { get; set; }
        public int FlowId { get; set; }
        public string Name { get; set; }
        public int Operator { get; set; }
        public int OperatorType { get; set; }
        public double MinTimes { get; set; }
        public double MaxTimes { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> NextStep { get; set; }
        public string Desc { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
