//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionskyOA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowProcess
    {
        public int Id { get; set; }
        public int FlowId { get; set; }
        public int StepId { get; set; }
        public int Operator { get; set; }
        public int Operation { get; set; }
        public string OperationDesc { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
